### ISSUE TITLE
Long datasets don't display correctly in the coda dashboard

### ISSUE THREAD

**Issue by as2388** [AfricasVoices/Operations-Dashboard#112]
When datasets have longer titles, the dashboard renders the name over two lines. I think this is desirable, however it draws those lines partially obscuring each other, which is confusing and hard to read. For example:

<img width="283" alt="image" src="https://user-images.githubusercontent.com/7963608/68679689-428cb500-0558-11ea-99b2-56cf000a87eb.png">

**Comment by DanielMwendwa** [comment]
This is an issue with screen size for I have tested this on some computers and it's okay. I think the issue lies on the custom implementation of the container's width I will have to adjust its values to see if I could mitigate this issue.

**Comment by as2388** [comment]
@DanielMwendwa is this fixed?

**Comment by DanielMwendwa** [comment]
> @DanielMwendwa is this fixed?

Yes
