### ISSUE TITLE
Graphs sometimes render misaligned bars 

### ISSUE THREAD

**Issue by as2388** [AfricasVoices/Operations-Dashboard#115]
See this example:
<img width="638" alt="image" src="https://user-images.githubusercontent.com/7963608/68877239-a9979e80-06fd-11ea-865e-47333972ea31.png">

I'm not sure what the cause is, but I think I've only observed this on pages that have been left open for a while, so suspect the redraw isn't working quite correctly.

**Comment by DanielMwendwa** [comment]
Haven't noticed this yet on my side. Gathering information on this.
