### ISSUE TITLE
404 on Login to Traffic Dashboards

### ISSUE THREAD

**Issue by as2388** [AfricasVoices/Operations-Dashboard#117]
Steps to reproduce:
 - Logout of the dashboard
 - Go to an engagement URL e.g. https://avf-dashboards.firebaseapp.com/media_engagement/worldbank_plr_sms_traffic.html
 - Follow the login process

Expected result:
I see the traffic dashboard.

Actual result:
Shown Firestore 404 page. I am logged in, and can see the traffic dashboard if I re-enter the correct url, but it's not obvious that I need to do that.

**Comment by DanielMwendwa** [comment]
This issue is handle in #124
