### ISSUE TITLE
Improve Message Coding table headers

### ISSUE THREAD

**Issue by as2388** [AfricasVoices/Operations-Dashboard#120]
We're seeing people interpret the dashboard as showing the total number of messages received in each dataset, and the fraction of WS/NC being interpreted as representative of the analysis dataset. These interpretations, however, are incorrect because the dashboard actually shows the number of unique messages and the fraction of those unique messages.

We could start to resolve this by renaming the table headers to e.g. "Unique Texts" rather than "Messages" etc. We might also add a description underneath the table that explains those columns and what can and cannot be inferred from them.

**Comment by DanielMwendwa** [comment]
@as2388 please send me some of the inference and description you would like to appear on the table, I would like to add to them on my descriptions.

**Comment by as2388** [comment]
I think we need to fix the naming of the headers first before we can write really good descriptions.

But sticking with the existing terminology for now, here's a first attempt:
- “Messages” shows the total number of unique texts in the dataset. Note that to reduce labelling load, Coda only displays each unique message text once, so this is not the total number of messages received.
- “Messages with a label” shows the number of unique texts which contain a *checked* (i.e. manually verified) label in at least one code scheme
- “Wrong scheme messages” shows the number of ‘messages with a label’ that contain a checked “WS (Wrong Scheme)” label.
- “NC messages” shows the number of ‘messages with a label’ that contain a checked “NC (Not Coded)” label.
