### ISSUE TITLE
Last Updated alert shows false positives

### ISSUE THREAD

**Issue by as2388** [AfricasVoices/Operations-Dashboard#139]
The 'last updated' timestamp often shows in red unnecessarily. For example: 
<img width="351" alt="image" src="https://user-images.githubusercontent.com/7963608/72827334-7f6cda80-3c72-11ea-8d38-7f30e8b7cbee.png">

Given that the sms service only runs for the previous complete ten-minute block since midnight (17:10-17:20) in this case and that it only runs once every 10 minutes, it could be until 17:30 until we get the block with the last update 17:10, so this shouldn't be red. I'd suggest waiting 25-30 minutes before reporting a problem.

**Comment by as2388** [comment]
I see this a lot when waking from sleep. Is there code which unsets this red alert once new data has been fetched?

**Comment by DanielMwendwa** [comment]
> I see this a lot when waking from sleep. Is there code which unsets this red alert once new data has been fetched?

No, sorry for the inconvenience. For now you have to refresh the page which is annoying. I'll have to fix it soon.
