### ISSUE TITLE
Operator names are being trimmed unnecessarily

### ISSUE THREAD

**Issue by as2388** [AfricasVoices/Operations-Dashboard#145]
See "kenyan telephone" here:
<img width="327" alt="image" src="https://user-images.githubusercontent.com/7963608/72913238-c7eccc80-3d34-11ea-836c-78d07b59cf37.png">

There's plenty of space to be able to see the complete text, yet it still gets partially obscured.

**Comment by DanielMwendwa** [comment]
reopened due to issue #157
