### ISSUE TITLE
Use stack bar charts for the number of messages

### ISSUE THREAD

**Issue by lukechurch** [AfricasVoices/Operations-Dashboard#37]
Hi @IsaackMwenda,

I think the numbers of the SMS will be easier to interpret as stacked bar charts rather than line charts. See e.g.

https://observablehq.com/@d3/stacked-bar-chart

or

https://bl.ocks.org/mbostock/1134768

Thanks in advance

**Comment by lukechurch** [comment]
Reassigning to Rita who will help out

@ritazagoni I think that @WHGTyen has some experience with this kind of chart in D3. Maybe have a chat with her?

**Comment by IsaackMwenda** [comment]
@lukechurch should we close this?
