### ISSUE TITLE
Move legend to the top right

### ISSUE THREAD

**Issue by lukechurch** [AfricasVoices/Operations-Dashboard#39]
The legends are hard to read at the moment - let's move them to the top right of the chart, stacked. A bit like here:

https://observablehq.com/@d3/stacked-bar-chart

**Comment by as2388** [comment]
<img width="180" alt="image" src="https://user-images.githubusercontent.com/7963608/65974589-16641b80-e465-11e9-89aa-0849bd3f177c.png">
@IsaackMwenda isn't this done?
