### ISSUE TITLE
Control x axis range

### ISSUE THREAD

**Issue by lukechurch** [AfricasVoices/Operations-Dashboard#40]
There are different scales that it's helpful to look at the graphs in. They are probably:

31 days
7 days
48 hours
24 hours

Let's add a drop down box that allows these to be selected.

**Comment by as2388** [comment]
Multiple individuals have suggested that 2 weeks is super useful, for comparison of this week vs last.

**Comment by DanielMwendwa** [comment]
> Multiple individuals have suggested that 2 weeks is super useful, for comparison of this week vs last.

@as2388 should I add a button for 2 weeks
