### ISSUE TITLE
Display last seen date on each chart

### ISSUE THREAD

**Issue by lukechurch** [AfricasVoices/Operations-Dashboard#52]
At the moment if the system updating the chart goes down, there's no easy way of seeing it.

We should have a date string for 'last update seen' which is normally formatted small and black - and becomes large and red if the value is more than 20 minutes old.

**Comment by IsaackMwenda** [comment]
@lukechurch should we close this?

**Comment by as2388** [comment]
> @lukechurch should we close this?

This isn't working very well for me:
<img width="609" alt="image" src="https://user-images.githubusercontent.com/7963608/65978091-fa637880-e46a-11e9-8249-4df4eba3bcaf.png">
This is showing as being scary and red but it's been less than ten minutes since the last update so that doesn't make sense...
