### ISSUE TITLE
Date filter on server side

### ISSUE THREAD

**Issue by lukechurch** [AfricasVoices/Operations-Dashboard#55]
Currently the charts pull all the data and filter on the client side. This causes needless read ops on the server side that we have to pay for.

Firestore queries can have filters added to them - so let's experiment with a range query on the server side (as well as filtering client side so that the chart doesn't get longer between reloads of the page)

**Comment by ritazagoni** [comment]
Currently dashboards display all data in 1-day stack view which doesn't seem necessary. I'm inclined to set it to 30 days, would that make sense @lukechurch?

**Comment by lukechurch** [comment]
Yup, please @ritazagoni
