### ISSUE TITLE
Only display operators in legend we expect messages from

### ISSUE THREAD

**Issue by ritazagoni** [AfricasVoices/Operations-Dashboard#61]
Currently we list all operators in charts legends regardless of whether we're operating in the area (in Somali projects). We should only have the ones we expect messages from. Should be set in firebase - active_projects?

**Comment by as2388** [comment]
This is easily configured in Firebase, but was added deliberately so we can track messages from operators who we didn't expect to hear from. We since observed this happening to us on OCHA.
