### ISSUE TITLE
Graphs Color scheme

### ISSUE THREAD

**Issue by DanielMwendwa** [AfricasVoices/Operations-Dashboard#77]
Duplicate of issue #69. Most of the colors in the color palettes we are using are indistinguishable when they are used on the graphs, instead we should provide color names that we can differentiate on the graphs.

**Comment by IsaackMwenda** [comment]
Thanks @DanielMwendwa If the issue has already been raised there is no need to raise it again. Instead, reference the earlier issue and enhance the description. Otherwise good job!
